[[12.1_Errors&Exceptions]]
[[12.2_Except_Review]]
[[12.3_Raising_Your_Own_Exceptions]]
[[12.4_Raise_vs_exception]]

---
## 12.1 Try/Except block

``` python
try:
  10 / 0
except Exception:
  print("can't divide by zero")
```

if we wanna access data from the exception:

``` python
try:
  10 / 0
except Exception as e:
  print(e)

# prints "division by zero"
```

[[12.1_Errors&Exceptions]]

---
## 12.3 PlayerID not found (raise Exception())

``` python
def get_player_record(player_id):
    if player_id == 1:
        return {"name": "Slayer", "level": 128}
    if player_id == 2:
        return {"name": "Dorgoth", "level": 300}
    if player_id == 3:
        return {"name": "Saruman", "level": 4000}
    raise Exception('player id not found')
```

```
---------------------------------
Inputs:
 * player_id: 1
Expecting: {'name': 'Slayer', 'level': 128}
Actual: {'name': 'Slayer', 'level': 128}
Pass
---------------------------------
Inputs:
 * player_id: 4
Expecting: player id not found
Actual: player id not found
Pass
---------------------------------
```

[[12.3_Raising_Your_Own_Exceptions]]

---
## 12.x raise not enough gold

``` python
def purchase_item(price, gold_available):
    if price > gold_available:
        raise Exception(f"{gold_available:.2f} is not enough for {price:.2f}")
    else:
        gold_available = gold_available - price
        return gold_available
```

## 12.x Mixin these two

``` python
def process_transactions(purchase_orders):
    leftovers = []
    for purchase_order in purchase_orders:
        try:
            price = purchase_order["price"]
            gold_available = purchase_order["gold_available"]
            leftover = purchase_item(price, gold_available)
            leftovers.append(leftover)
        # so if try doesn't work, it prints it as an exception. only adding transactions that went thru to leftovers.
        except Exception as e:
            print(e)
    return leftovers
```

```
Processing transactions...
2.00 is not enough for 5.00
5.20 is not enough for 20.01
6.00 is not enough for 40.20
2.30 is not enough for 12.00
Transactions complete!
Leftover amounts for successful purchases:
 * 115.00
 * 252.96
 * 219.01
 * 0.00
```

## Assignment
Complete the `process_transactions` function. It takes a list of purchase orders. Each order is a dictionary. Look through the `main()` function to see the shape of this data.

- First, create an empty list of `leftovers`.
- Then, loop over the list of `purchase_orders`.
- For each order, try to process the order with the `purchase_item` function. If an exception is raised, print the raised exception.
- If there is not an error, then the purchase was successful. Append the remaining money to the `leftovers` list. If there is an error, don't add anything to the `leftovers`.
- Be sure to loop over the entire list of purchase orders.
- At the end of the loop, return the `leftovers` list.

Keep the same order of purchases, but with the unsuccessful purchases removed.

---

[[11.0_Sets]]
[[13.0_Challenges]]